version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g @aws-amplify/cli
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  base-directory: build
  files:
    - '**/*'