version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
    - npm install -g @aws-amplify/cli
  build:
    commands:
    - cd frontend && npm install
    - cd ../backend && npm install
  post_build:
    commands:
    - ./deploy.sh

artifacts:
  files:
  - '**/*'